CREATE VIEW COMPOSITE_SCHOOL_ATTENDANCE_ANALYSIS AS
SELECT
    M.*,
    A.Attendance_pct,
    P.ICSEA_VALUE,
    P.LEVEL_OF_SCHOOLING,
    P.LATEST_YEAR_ENROLMENT_FTE,
    P.INDIGENOUS_PCT,
    P.LBOTE_PCT,
    P.SELECTIVE_SCHOOL,
    P.OPPORTUNITY_CLASS,
    P.SCHOOL_SPECIALTY_TYPE,
    P.SCHOOL_SUBTYPE,
    P.PRESCHOOL_IND,
    P.DISTANCE_EDUCATION,
    P.INTENSIVE_ENGLISH_CENTRE,
    P.SCHOOL_GENDER,
    P.LATE_OPENING_SCHOOL,
    P.ASGS_REMOTENESS,
    P.LATITUDE,
    P.LONGITUDE
FROM
    MULTI_AGE_COMPOSITE_UNPIVOTED M
JOIN
    STUDENT_ATTENDANCE_UNPIVOTED A ON M.SCHOOL_CODE = A.School_Code AND M.YEAR = A.Year
JOIN
    PUBLIC_SCHOOL_NSW_MASTER_DATASET P ON M.SCHOOL_CODE = P.SCHOOL_CODE;